### ISSUE TITLE
Hide mobile navbar on-scroll

### ISSUE THREAD

**Issue by BrianRuizy** [BrianRuizy/gatsby-minimal-portfolio#6]
Make auto-hide toggleable for the mobile navbar

**Comment by sid-r-singh** [comment]
Seriously you want to do this ? Please please, I love that navbar & I want it on screen always. In case you want this feature to be implemented, please provide a option to enable/disable this feature, so that we can keep using it.

**Comment by BrianRuizy** [comment]
@sid-r-singh you're right, good idea. I'll make it optional to be always shown are auto-hide

**Comment by sid-r-singh** [comment]
Thanks a lot 😄
